version: "3.9"

services:
  seq:
    image: datalust/seq
    container_name: seq
    ports:
      - 5340:80
      - 5341:5341
    environment:
      - ACCEPT_EULA=Y
      - BASE_URI=https://seq
    volumes:
      - C:/Development/Data/Seq:/data
    restart: unless-stopped

  weather.api:
    image: weather.api
    container_name: weather.api
    build:
      context: .
      dockerfile: WeatherApi/Dockerfile
    depends_on:
      - seq
    ports:
      - 9991:80
    environment:
      - Serilog:MinimumLevel=Information
      - Serilog:Using:[0]=Serilog.Sinks.Seq
      - Serilog:WriteTo:[0]:Name=Seq
      - Serilog:WriteTo:[0]:Args:serverUrl=http://seq:5341
      - Serilog:Properties:Application=WebApi
      - Serilog:Properties:Environment=Local Development
      - Weather:City=Sydney
      - Weather:TemperatureUnit=F
    restart: unless-stopped

  weather.ui:
    image: weather.ui
    container_name: weather.ui
    build:
      context: ./WeatherUi
      dockerfile: Dockerfile
      args:
        webapiurl: http://127.0.0.1:9991
    depends_on:
      - weatherapi
    ports:
      - 9992:80
    restart: unless-stopped
